"""Shared deterministic small-variant identity helpers.

These helpers deliberately trim only VCF padding.  They do not claim
reference-aware left-shift equivalence.
"""

from __future__ import annotations

from collections.abc import Mapping


CLINVAR_REFSEQ_BASES = {
    **{str(chromosome): f"NC_{chromosome:06d}" for chromosome in range(1, 23)},
    "X": "NC_000023", "Y": "NC_000024", "MT": "NC_012920",
}
CLINVAR_REFSEQ_VERSIONS = {
    "GRCh37": {"1": 10, "2": 11, "3": 11, "4": 11, "5": 9, "6": 11, "7": 13, "8": 10, "9": 11, "10": 10, "11": 9, "12": 11, "13": 10, "14": 8, "15": 9, "16": 9, "17": 10, "18": 9, "19": 9, "20": 10, "21": 8, "22": 10, "X": 10, "Y": 9, "MT": 1},
    "GRCh38": {"1": 11, "2": 12, "3": 12, "4": 12, "5": 10, "6": 12, "7": 14, "8": 11, "9": 12, "10": 11, "11": 10, "12": 12, "13": 11, "14": 9, "15": 10, "16": 10, "17": 11, "18": 10, "19": 10, "20": 11, "21": 9, "22": 11, "X": 11, "Y": 10, "MT": 1},
}


def normalize_chromosome(value: object) -> str | None:
    normalized = str(value).strip().upper()
    if normalized.startswith("CHR"):
        normalized = normalized[3:]
    if normalized == "M":
        normalized = "MT"
    if normalized in {"X", "Y", "MT"}:
        return normalized
    return str(int(normalized)) if normalized.isdigit() and 1 <= int(normalized) <= 22 else None


def normalize_variant_edit(variant: Mapping[str, object]) -> tuple[str, int, str, str] | None:
    chromosome = normalize_chromosome(variant.get("chrom"))
    reference = str(variant.get("ref", "")).strip().upper()
    alternate = str(variant.get("alt", "")).strip().upper()
    position = variant.get("pos")
    if (chromosome is None or not isinstance(position, int) or isinstance(position, bool)
            or position < 1 or not reference or not alternate
            or not set(reference).issubset({"A", "C", "G", "T"})
            or not set(alternate).issubset({"A", "C", "G", "T"})
            or reference == alternate):
        return None
    start = position
    while reference and alternate and reference[0] == alternate[0]:
        reference, alternate, start = reference[1:], alternate[1:], start + 1
    while reference and alternate and reference[-1] == alternate[-1]:
        reference, alternate = reference[:-1], alternate[:-1]
    return chromosome, start, reference, alternate


def format_genomic_hgvs(sequence: str, start: int, reference: str, alternate: str) -> str:
    prefix = f"{sequence}:g."
    if not reference and alternate:
        return f"{prefix}{start - 1}_{start}ins{alternate}"
    if reference and not alternate:
        end = start + len(reference) - 1
        return f"{prefix}{start if start == end else f'{start}_{end}'}del"
    if len(reference) == 1 and len(alternate) == 1:
        return f"{prefix}{start}{reference}>{alternate}"
    end = start + len(reference) - 1
    return f"{prefix}{start if start == end else f'{start}_{end}'}delins{alternate}"


def normalized_genomic_hgvs(variant: Mapping[str, object], genome_build: str) -> tuple[str, tuple[str, int, str, str]] | None:
    edit = normalize_variant_edit(variant)
    if edit is None or genome_build not in CLINVAR_REFSEQ_VERSIONS:
        return None
    chromosome, start, reference, alternate = edit
    version = CLINVAR_REFSEQ_VERSIONS[genome_build].get(chromosome)
    if version is None:
        return None
    return format_genomic_hgvs(f"{CLINVAR_REFSEQ_BASES[chromosome]}.{version}", start, reference, alternate), edit


def parse_normalized_genomic_hgvs(value: object) -> tuple[str, int, str, str] | None:
    """Parse precisely the HGVS forms generated by ``format_genomic_hgvs``."""
    import re
    text = str(value).strip().upper()
    match = re.fullmatch(r"(NC_\d+\.\d+):G\.(\d+)([ACGT])>([ACGT])", text)
    if match:
        return match.group(1), int(match.group(2)), match.group(3), match.group(4)
    match = re.fullmatch(r"(NC_\d+\.\d+):G\.(\d+)(?:_(\d+))?DELINS([ACGT]+)", text)
    if match:
        start, end = int(match.group(2)), int(match.group(3) or match.group(2))
        return match.group(1), start, "?" * (end - start + 1), match.group(4)
    match = re.fullmatch(r"(NC_\d+\.\d+):G\.(\d+)(?:_(\d+))?DEL", text)
    if match:
        start, end = int(match.group(2)), int(match.group(3) or match.group(2))
        return match.group(1), start, "?" * (end - start + 1), ""
    match = re.fullmatch(r"(NC_\d+\.\d+):G\.(\d+)_(\d+)INS([ACGT]+)", text)
    if match:
        return match.group(1), int(match.group(2)) + 1, "", match.group(4)
    return None
